apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: guestbook
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-guestbook # Caminho dentro do repositório Git onde os manifests estão localizadoss
    repoURL: https://github.com/argoproj/argocd-example-apps # URL do repositório Git da aplicaçãos
    targetRevision: HEAD # Pode ser uma branch, tag ou commit hash
  syncPolicy:
    automated: # Sincronização automática (ArgoCD verificará mudanças e aplicará automaticamente)
      enabled: true
    syncOptions:
    - CreateNamespace=true